# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: aad770e32c2550f9ce277ba4887abb7b581da14e720f3252a61bb48699a45d0aa0013f90fe2432106ab9f1dd67401b0d6a0809ea0acfc8fb5785447aaec8729d

test:
  secret_key_base: 543a4c570bdb6e9876888a6311c1ab1ed5715364fdc8ab7973866373b90fe90cde639af7d6a10ad7d7de2b2e2c0e6feb25e0ab73f15ce035cb40b03e82fad1f2

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
